WebFlug/Controllers/OfferController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using WebFlug.Models;

namespace WebFlug.Controllers
{
    public class OfferController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Offer
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var offers = db.offers.Include(o => o.orders);
            return View(offers.ToList());
        }

        [Authorize(Roles = "User")]
        public ActionResult OfferAccepted()
        {
            var UserId = User.Identity.GetUserId();
            var offers = db.offers.Where(a => a.UserId == UserId && a.OfferSatatus == "Accepted").ToList();
            return View(offers);
        }

        [Authorize(Roles = "User")]
        public ActionResult ConfirmedOffers()
        {
            var UserId = User.Identity.GetUserId();
            var offers = db.offers.Where(a => a.UserId == UserId && a.OfferSatatus == "Confirmed").ToList();
            return View(offers);
        }

        [Authorize(Roles = "User")]
        public ActionResult DoneOffers()
        {
            var UserId = User.Identity.GetUserId();
            var offers = db.offers.Where(a => a.UserId == UserId && a.OfferSatatus == "Done").ToList();
            return View(offers);
        }
        
        // GET: MyOffers
        [Authorize(Roles = "User")]
        public ActionResult MyOffers()
        {
            var UserId = User.Identity.GetUserId();
            var offers = db.offers.Where(a => a.UserId == UserId && a.OfferSatatus == "Pending").ToList();
            return View(offers);
        }

        // GET: Offer/MakeOffer/5
        [Authorize(Roles = "User")]
        public ActionResult MakeOffer()
        {
            return View();
        }

        // POST: Offer/MakeOffer/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User")]
        public ActionResult MakeOffer(string TravellerReward, DateTime DeliverDate)
        {
            var userID = User.Identity.GetUserId();
            var orderID = (int)Session["Order_Id"];

            var offer = new Offers();

            if (ModelState.IsValid)
            {
                offer.Order_Id = orderID;

                offer.UserId = userID;

                offer.OfferSatatus = "Pending";

                DateTime today = DateTime.Today;
                today.ToString("dd-MM-yyyy");
                offer.CreationDate = today;

                offer.TravellerReward = TravellerReward;
                offer.DeliverDate = DeliverDate;

                db.offers.Add(offer);
                db.SaveChanges();
                return RedirectToAction("Index","Home");
            }

            return View();
        }
    
        // GET: Offer/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Offers offers = db.offers.Find(id);
            if (offers == null)
            {
                return HttpNotFound();
            }
            return View(offers);
        }

        // GET: Offer/Edit/5
        [Authorize(Roles = "User")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Offers offers = db.offers.Find(id);
            if (offers == null)
            {
                return HttpNotFound();
            }
           
            return View(offers);
        }

        // POST: Offer/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User")]
        public ActionResult Edit(Offers offers)
        {
            if (ModelState.IsValid)
            {
                db.Entry(offers).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("MyOffers");
            }
            return View(offers);
        }

        // GET: Offer/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Offers offers = db.offers.Find(id);
            if (offers == null)
            {
                return HttpNotFound();
            }
            return View(offers);
        }

        // POST: Offer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Offers offers = db.offers.Find(id);
            db.offers.Remove(offers);
            db.SaveChanges();
            return RedirectToAction("MyOffers");
        }

        //
        public Offers RetriveOfferByID(int ID)
        {
            var model = db.offers.FirstOrDefault(x => x.Offer_Id == ID);
            return model;
        }

        //
        public Orders RetriveOrderByID(int ID)
        {
            var model = db.orders.FirstOrDefault(x => x.Order_Id == ID);
            return model;
        }

        // GET: Order/ConfirmBuy/5
        public ActionResult ConfirmBuy()
        {
            return View();
        }

        // POST: Order/ConfirmBuy/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ConfirmBuy(int id)
        {
            var Offermodel = RetriveOfferByID(id);
            Offermodel.OfferSatatus = "Confirmed";
            UpdateModel<Offers>(Offermodel);
            db.SaveChanges();

            var OrderModel = RetriveOrderByID(Offermodel.Order_Id);
            OrderModel.OrderSatatus = "Confirmed";
            UpdateModel<Orders>(OrderModel);
            db.SaveChanges();

            return RedirectToAction("MyOffers");
        }

        //
        public ActionResult DoneDelivering()
        {
            return View();
        }

        // POST: Order/ConfirmBuy/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DoneDelivering(int id)
        {
            var Offermodel = RetriveOfferByID(id);
            Offermodel.OfferSatatus = "Done";
            UpdateModel<Offers>(Offermodel);
            db.SaveChanges();
            
            return RedirectToAction("SendEmail","EmailSetup");
        }

        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebFlug/Controllers/TripController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebFlug.Models;

namespace WebFlug.Controllers
{
    public class TripController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

        // GET: Trip
        [Authorize(Roles = "Admin")]
        public IEnumerable<Trips> GetTrips()
        {
            var trips = db.trips.ToList();
            return trips;
        }

        //Index trip
        public ActionResult Index()
        {
            var orders = GetTrips();
            return View(orders);
        }

        // GET: Trip/Create
        public ActionResult Create()
          {
              return View();
          }

        // POST: Trip/Create
        [HttpPost]
        [ValidateAntiForgeryToken]//prevent cross-site request forgery attacks
        public ActionResult Create(Trips trip, HttpPostedFileBase upload)
        {
            var userID = User.Identity.GetUserId();

              if (ModelState.IsValid)
              {
                trip.UserId = userID;

                string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                upload.SaveAs(path);
                trip.TicketPhoto = upload.FileName;

                trip.TripCreationDate = DateTime.Now;

                db.trips.Add(trip);
                db.SaveChanges();
                return RedirectToAction("MyTrips");
              }

              return View(trip);
          }

        //Get : user trips 
        public ActionResult MyTrips()
        {
            var UserId = User.Identity.GetUserId();
            var trips = db.trips.Where(a => a.UserId == UserId);
            return View(trips.ToList());
        }

        // GET: Trip/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trips trip = db.trips.Find(id);
            if (trip == null)
            {
                return HttpNotFound();
            }
            return View(trip);
        }

        // GET: Trip/Details/5
        public ActionResult VisitorDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trips trip = db.trips.Find(id);
            if (trip == null)
            {
                return HttpNotFound();
            }
            return View(trip);
        }

        // GET: Trip/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trips trip = db.trips.Find(id);
            if (trip == null)
            {
                return HttpNotFound();
            }
            return View(trip);
        }

        // POST: Trip/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Trips trip, int id, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null)
                {
                    string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                    upload.SaveAs(path);
                    trip.TicketPhoto = upload.FileName;
                }
                trip.Trip_Id = id;                
                db.Entry(trip).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("MyTrips");
            }
            return View(trip);
        }

        // GET: Trips/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trips trip = db.trips.Find(id);
            if (trip == null)
            {
                return HttpNotFound();
            }
            return View(trip);
        }

        // POST: Trips/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Trips trip = db.trips.Find(id);
            db.trips.Remove(trip);
            db.SaveChanges();
            return RedirectToAction("MyTrips");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebFlug/Views/Shared/Notifi_Inbox.cshtml
@using Microsoft.AspNet.Identity
@using WebFlug.Models
@if (Request.IsAuthenticated)
{
    @Html.AntiForgeryToken()
    <div class="wrap-icon-header flex-w flex-r-m h-full" style="margin-left:70px;">
        <div class="flex-c-m h-full p-r-24">

            <div class="icon-header-item cl2 hov-cl1 trans-04 p-lr-11">
                <i class="zmdi zmdi-inbox"> <a href="~/Views/"></a></i>
            </div>
        </div>

        <div class="flex-c-m h-full p-l-18 p-r-25 bor5">
            <div class="icon-header-item cl2 hov-cl1 trans-04 p-lr-11 icon-header-noti js-show-cart" data-notify="2">
                <i class="zmdi zmdi-notifications"></i>
            </div>
        </div>

        <div class="flex-c-m h-full p-lr-19">
                <div class="icon-header-item cl2 hov-cl1 trans-04 p-lr-11 js-show-sidebar">

                    <img src="~/Content/images/nada.jpg" alt="Avatar" style="border-radius: 50%; width: 40px; height: 40px;">

                </div>
            </div>


    </div>
}
else
{
}

WebFlug/Views/Shared/Order_Offer.cshtml
@using Microsoft.AspNet.Identity
@using WebFlug.Models

@if (Request.IsAuthenticated)
{
    <li>
        <a href="@Url.Action("Index", "Home")">Home</a>
    </li>

    <li>
        <a href="@Url.Action("ViewOldOrders", "Order")">Orders</a>
    </li>

    <li class="label1" data-label1="hot">
        <a href="@Url.Action("MyOffers", "Offer")">Offers</a>
    </li>

    <li>
        <a href="@Url.Action("MyTrips", "Trip")">Trips</a>
    </li>
}

WebFlug/Views/Shared/_NavBar.cshtml
  <!-- Header -->
<header class="header-v2">
    <!-- Header desktop -->
    <div class="container-menu-desktop trans-03">
        <div class="wrap-menu-desktop">
            <nav class="limiter-menu-desktop p-l-45">

                <!-- Logo desktop -->
                <a href="#" class="logo">
                    <img src="~/Content/images/icons/fluglogo.png" alt="IMG-LOGO">
                </a>

                <!-- Menu desktop -->
                <div class="menu-desktop">
                    <ul class="main-menu">
                        <li>
                            <a href="index.cshtml">Home</a>
                        </li>

                        <li>
                            @Html.ActionLink("Order", "ViewOldOrders","Order")
                        </li>

                        <li class="label1" data-label1="hot">
                            <a href=("shoping-cart.html")>Offers</a>
                        </li>
                        <li>
                            <a href=@Url.Content("/Content/about.html")>About</a>
                        </li>

                        <li>
                            <a href=@Url.Content("/Content/contact.html")>Contact</a>
                        </li>

                        @Html.Partial("_LoginPartial")
                    </ul>
                </div>
                <style>
                    .icon-header-item a {
                        color: #333;
                        font-family: Poppins-Regular;
                        font-size: 20px;
                    }

                        .icon-header-item a:hover {
                            color: #02cf68;
                        }
                </style>
                <div class="wrap-icon-header flex-w flex-r-m h-full">
                    <div class="flex-c-m h-full p-r-24">
                        <div class="icon-header-item">
                            <a href="/Content/Login.html">Login</a>
                        </div>
                    </div>

                    <div class="flex-c-m h-full p-r-24">
                        <div class="icon-header-item">
                            <a href="RegistrationForm.html"> Register</a>
                        </div>
                    </div>



                </div>
            </nav>

        </div>

        </div>

        <!-- Header Mobile -->
        <div class="wrap-header-mobile">
            <!-- Logo moblie -->
            <div class="logo-mobile">
                <a href="index.html"><img src=@Url.Content("/Content/images/icons/fluglogo.png") alt="IMG-LOGO"></a>
            </div>

            <div class="wrap-icon-header flex-w flex-r-m h-full">
                <div class="flex-c-m h-full p-r-24">
                    <div class="icon-header-item cl2 hov-cl1 trans-04 p-lr-11 js-show-modal-search">
                        <i class="zmdi zmdi-search"></i>
                    </div>
                </div>

                <div class="flex-c-m h-full p-l-18 p-r-25 bor5">
                    <div class="icon-header-item cl2 hov-cl1 trans-04 p-lr-11 icon-header-noti js-show-cart" data-notify="2">
                        <i class="zmdi zmdi-notifications"></i>
                    </div>
                </div>

                <div class="flex-c-m h-full p-lr-19">
                    <div class="icon-header-item cl2 hov-cl1 trans-04 p-lr-11 js-show-sidebar">
                        <i class="zmdi zmdi-menu"></i>
                    </div>


                </div>
            </div>

            <!-- Button show menu -->
            <div class="btn-show-menu-mobile hamburger hamburger--squeeze">
                <span class="hamburger-box">
                    <span class="hamburger-inner"></span>
                </span>
            </div>
        </div>


        <!-- Menu Mobile -->
        <div class="menu-mobile">
            <ul class="main-menu-m">
                <li>
                    <a href="index.html">Home</a>
                    <ul class="sub-menu-m">
                        <li><a href="index.html">Homepage 1</a></li>
                        <li><a href="home-02.html">Homepage 2</a></li>
                        <li><a href="home-03.html">Homepage 3</a></li>
                    </ul>
                    <span class="arrow-main-menu-m">
                        <i class="fa fa-angle-right" aria-hidden="true"></i>
                    </span>
                </li>

                <li>
                    <a href="product.html">Shop</a>
                </li>

                <li>
                    <a href="shoping-cart.html" class="label1 rs1" data-label1="hot">Features</a>
                </li>

                <li>
                    <a href="blog.html">Blog</a>
                </li>

                <li>
                    <a href="about.html">About</a>
                </li>

                <li>
                    <a href="contact.html">Contact</a>
                </li>
            </ul>
        </div>

        <!-- Modal Search -->
        <div class="modal-search-header flex-c-m trans-04 js-hide-modal-search">
            <div class="container-search-header">
                <button class="flex-c-m btn-hide-modal-search trans-04 js-hide-modal-search">
                    <img src="images/icons/icon-close2.png" alt="CLOSE">
                </button>

                <form class="wrap-search-header flex-w p-l-15">
                    <button class="flex-c-m trans-04">
                        <i class="zmdi zmdi-search"></i>
                    </button>
                    <input class="plh3" type="text" name="search" placeholder="Search...">
                </form>
            </div>
        </div>
</header>

<!-- Cart -->
<!-- Sidebar -->
<aside class="wrap-sidebar js-sidebar">
    <div class="s-full js-hide-sidebar"></div>

    <div class="sidebar flex-col-l p-t-22 p-b-25">
        <div class="flex-r w-full p-b-30 p-r-27">
            <div class="fs-35 lh-10 cl2 p-lr-5 pointer hov-cl1 trans-04 js-hide-sidebar">
                <i class="zmdi zmdi-close"></i>
            </div>
        </div>

        <div class="sidebar-content flex-w w-full p-lr-65 js-pscroll">
            <ul class="sidebar-link w-full">
                <li class="p-b-13">
                    <a href="index.html" class="stext-102 cl2 hov-cl1 trans-04">
                        Home
                    </a>
                </li>

                <li class="p-b-13">
                    <a href="#" class="stext-102 cl2 hov-cl1 trans-04">
                        My Wishlist
                    </a>
                </li>

                <li class="p-b-13">
                    <a href="#" class="stext-102 cl2 hov-cl1 trans-04">
                        My Account
                    </a>
                </li>

                <li class="p-b-13">
                    <a href="#" class="stext-102 cl2 hov-cl1 trans-04">
                        Track Oder
                    </a>
                </li>

                <li class="p-b-13">
                    <a href="#" class="stext-102 cl2 hov-cl1 trans-04">
                        Refunds
                    </a>
                </li>

                <li class="p-b-13">
                    <a href="#" class="stext-102 cl2 hov-cl1 trans-04">
                        Help & FAQs
                    </a>
                </li>
            </ul>

        </div>

        <div class="flex-w flex-sb p-t-36 gallery-lb">
            <!-- item gallery sidebar -->
            <div class="wrap-item-gallery m-b-10">
                <a class="item-gallery bg-img1" href="images/gallery-01.jpg" data-lightbox="gallery"
                   style="background-image: url('images/gallery-01.jpg');"></a>
            </div>

            <!-- item gallery sidebar -->
            <div class="wrap-item-gallery m-b-10">
                <a class="item-gallery bg-img1" href="images/gallery-02.jpg" data-lightbox="gallery"
                   style="background-image: url('images/gallery-02.jpg');"></a>
            </div>

            <!-- item gallery sidebar -->
            <div class="wrap-item-gallery m-b-10">
                <a class="item-gallery bg-img1" href="images/gallery-03.jpg" data-lightbox="gallery"
                   style="background-image: url('images/gallery-03.jpg');"></a>
            </div>

            <!-- item gallery sidebar -->
            <div class="wrap-item-gallery m-b-10">
                <a class="item-gallery bg-img1" href="images/gallery-04.jpg" data-lightbox="gallery"
                   style="background-image: url('images/gallery-04.jpg');"></a>
            </div>

            <!-- item gallery sidebar -->
            <div class="wrap-item-gallery m-b-10">
                <a class="item-gallery bg-img1" href="images/gallery-05.jpg" data-lightbox="gallery"
                   style="background-image: url('images/gallery-05.jpg');"></a>
            </div>

            <!-- item gallery sidebar -->
            <div class="wrap-item-gallery m-b-10">
                <a class="item-gallery bg-img1" href="images/gallery-06.jpg" data-lightbox="gallery"
                   style="background-image: url('images/gallery-06.jpg');"></a>
            </div>

            <!-- item gallery sidebar -->
            <div class="wrap-item-gallery m-b-10">
                <a class="item-gallery bg-img1" href="images/gallery-07.jpg" data-lightbox="gallery"
                   style="background-image: url('images/gallery-07.jpg');"></a>
            </div>

            <!-- item gallery sidebar -->
            <div class="wrap-item-gallery m-b-10">
                <a class="item-gallery bg-img1" href="images/gallery-08.jpg" data-lightbox="gallery"
                   style="background-image: url('images/gallery-08.jpg');"></a>
            </div>

            <!-- item gallery sidebar -->
            <div class="wrap-item-gallery m-b-10">
                <a class="item-gallery bg-img1" href="images/gallery-09.jpg" data-lightbox="gallery"
                   style="background-image: url('images/gallery-09.jpg');"></a>
            </div>
        </div>
    </div>

    <div class="sidebar-gallery w-full">
        <span class="mtext-101 cl5">
            About Us
        </span>

        <p class="stext-108 cl6 p-t-27">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur maximus vulputate hendrerit. Praesent faucibus erat vitae rutrum gravida. Vestibulum tempus mi enim, in molestie sem fermentum quis.
        </p>
    </div>

</aside>


<!-- Cart -->
<div class="wrap-header-cart js-panel-cart">
    <div class="s-full js-hide-cart"></div>

    <div class="header-cart flex-col-l p-l-65 p-r-25">
        <div class="header-cart-title flex-w flex-sb-m p-b-8">
            <span class="mtext-103 cl2">
                Your Cart
            </span>

            <div class="fs-35 lh-10 cl2 p-lr-5 pointer hov-cl1 trans-04 js-hide-cart">
                <i class="zmdi zmdi-close"></i>
            </div>
        </div>

        <div class="header-cart-content flex-w js-pscroll">
            <ul class="header-cart-wrapitem w-full">
                <li class="header-cart-item flex-w flex-t m-b-12">
                    <div class="header-cart-item-img">
                        <img src="images/item-cart-01.jpg" alt="IMG">
                    </div>

                    <div class="header-cart-item-txt p-t-8">
                        <a href="#" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
                            White Shirt Pleat
                        </a>

                        <span class="header-cart-item-info">
                            1 x $19.00
                        </span>
                    </div>
                </li>

                <li class="header-cart-item flex-w flex-t m-b-12">
                    <div class="header-cart-item-img">
                        <img src="images/item-cart-02.jpg" alt="IMG">
                    </div>

                    <div class="header-cart-item-txt p-t-8">
                        <a href="#" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
                            Converse All Star
                        </a>

                        <span class="header-cart-item-info">
                            1 x $39.00
                        </span>
                    </div>
                </li>

                <li class="header-cart-item flex-w flex-t m-b-12">
                    <div class="header-cart-item-img">
                        <img src="images/item-cart-03.jpg" alt="IMG">
                    </div>

                    <div class="header-cart-item-txt p-t-8">
                        <a href="#" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
                            Nixon Porter Leather
                        </a>

                        <span class="header-cart-item-info">
                            1 x $17.00
                        </span>
                    </div>
                </li>
            </ul>

            <div class="w-full">
                <div class="header-cart-total w-full p-tb-40">
                    Total: $75.00
                </div>

                <div class="header-cart-buttons flex-w w-full">
                    <a href="shoping-cart.html" class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-r-8 m-b-10">
                        View Cart
                    </a>

                    <a href="shoping-cart.html" class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-b-10">
                        Check Out
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

WebFlug/Views/Shared/_footer.cshtml
   <!-- Footer -->
<footer class="bg3 p-t-75 p-b-32">
    <div class="container">
        <div class="row">


            <div class="col-sm-6 col-lg-3 p-b-50">
                <h4 class="stext-301 cl0 p-b-30">
                    Help
                </h4>

                <ul>
                    <li class="p-b-10">
                        <a href="#" class="stext-107 cl7 hov-cl1 trans-04">
                            Track Order
                        </a>
                    </li>

                    <li class="p-b-10">
                        <a href="#" class="stext-107 cl7 hov-cl1 trans-04">
                            Returns
                        </a>
                    </li>

                    <li class="p-b-10">
                        <a href="#" class="stext-107 cl7 hov-cl1 trans-04">
                            Shipping
                        </a>
                    </li>

                    <li class="p-b-10">
                        <a href="#" class="stext-107 cl7 hov-cl1 trans-04">
                            FAQs
                        </a>
                    </li>
                </ul>
            </div>

            <div class="col-sm-6 col-lg-3 p-b-50">
                <h4 class="stext-301 cl0 p-b-30">
                    GET IN TOUCH
                </h4>

                <p class="stext-107 cl7 size-201">
                    Any questions? Visit our social media
                </p>

                <div class="p-t-27">
                    <a href="#" class="fs-18 cl7 hov-cl1 trans-04 m-r-16">
                        <i class="fa fa-facebook"></i>
                    </a>

                    <a href="#" class="fs-18 cl7 hov-cl1 trans-04 m-r-16">
                        <i class="fa fa-instagram"></i>
                    </a>

                    <a href="#" class="fs-18 cl7 hov-cl1 trans-04 m-r-16">
                        <i class="fa fa-pinterest-p"></i>
                    </a>
                </div>
            </div>

            <div class="col-sm-6 col-lg-3 p-b-50">
                <h4 class="stext-301 cl0 p-b-30">
                    Newsletter
                </h4>

                <form>
                    <div class="wrap-input1 w-full p-b-4">
                        <input class="input1 bg-none plh1 stext-107 cl7" type="text" name="email" placeholder="email@example.com">
                        <div class="focus-input1 trans-04"></div>
                    </div>

                    <div class="p-t-18">
                        <button class="flex-c-m stext-101 cl0 size-103 bg1 bor1 hov-btn2 p-lr-15 trans-04">
                            Subscribe
                        </button>
                    </div>
                </form>
            </div>
        </div>



        <p class="stext-107 cl6 txt-center">
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;
            <script>document.write(new Date().getFullYear());</script> All rights reserved
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->

        </p>
    </div>

</footer>
<!-- Back to top -->
<div class="btn-back-to-top" id="myBtn">
    <span class="symbol-btn-back-to-top">
        <i class="zmdi zmdi-chevron-up"></i>
    </span>
</div>