WebFlug/Controllers/EmailSetupController.cs
using System.Net;
using System.Net.Mail;
using System.Web.Mvc;
using WebFlug.Models;

namespace WebFlug.Controllers
{
    public class EmailSetupController : Controller
    {
        // GET: Feedback
        [Authorize(Roles = "User")]
        public ActionResult SendEmail()
        {
            return View();
        }

        // Feedback
        [HttpPost]
        [Authorize(Roles = "User")]
        public ActionResult SendEmail(Email model)
        {
            MailMessage mm = new MailMessage("flugapplication@gmail.com", "naghamamr@gmail.com");
            mm.Subject = "Feedback / Question";
            mm.Body = model.Body;
            mm.IsBodyHtml = false;

            SmtpClient smtp = new SmtpClient();
            smtp.Host = "smtp.gmail.com";
            smtp.Port = 587;
            smtp.EnableSsl = true;

            NetworkCredential nc = new NetworkCredential("flugapplication@gmail.com", "@El7el7el7");
            smtp.UseDefaultCredentials = true;
            smtp.Credentials = nc;
            smtp.Send(mm);
            ViewBag.Message = "your Feedback / Question has been sent succefully";

            return RedirectToAction("Index","Home");
        }

        // GET: 
        [Authorize(Roles = "User")]
        public ActionResult ContactUs()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "User")]
        public ActionResult ContactUs(Email model)
        {
            MailMessage mm = new MailMessage("flugapplication@gmail.com", "naghamamr@gmail.com");
            mm.Subject = "Feedback / Question";
            mm.Body = model.Body;
            mm.IsBodyHtml = false;

            SmtpClient smtp = new SmtpClient();
            smtp.Host = "smtp.gmail.com";
            smtp.Port = 587;
            smtp.EnableSsl = true;

            NetworkCredential nc = new NetworkCredential("flugapplication@gmail.com", "@El7el7el7");
            smtp.UseDefaultCredentials = true;
            smtp.Credentials = nc;
            smtp.Send(mm);
            ViewBag.Message = "your Feedback / Question has been sent succefully";

            return RedirectToAction("Index", "Home");
        }
    }
}

WebFlug/Views/EmailSetup/ContactUs.cshtml
@model WebFlug.Models.Email
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <title>Flug/Contact Us</title>
</head>
<!-- Title page -->
<section class="bg-img1 txt-center p-lr-15 p-tb-92" style="background-image: url('/Content/images/aboutus.jpg');">
    <h2 class="ltext-105 cl0 txt-center">
        Contact
    </h2>
</section>

<!-- Content page -->
@using (Html.BeginForm("SendEmail", "EmailSetup", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <section class="bg0 p-t-104 p-b-116">
        <div class="container">
            <div class="flex-w flex-tr">
                <div class="size-210 bor10 p-lr-70 p-t-55 p-b-70 p-lr-15-lg w-full-md">
                    <form>
                        <h4 class="mtext-105 cl2 txt-center p-b-30">
                            Send Us A Message
                        </h4>
                        @*@<div class="bor8 m-b-20 how-pos4-parent">
                                <input class="stext-111 cl2 plh3 size-116 p-l-62 p-r-30" type="text" name="email" placeholder="Your Email Address">
                                <img class="how-pos4 pointer-none" src="/Content/images/icons/icon-email.png" alt="ICON">
                            </div>*@
                        <div class="bor8 m-b-30">
                            @Html.TextAreaFor(model => model.Body, new { @class = "stext-111 cl2 plh3 size-120 p-lr-28 p-tb-25", placeholder = "How Can We Help? Please type your mail at the end of the message" })
                        </div>
                        <button class="flex-c-m stext-101 cl0 size-121 bg3 bor1 hov-btn3 p-lr-15 trans-04 pointer">
                            Submit
                        </button>
                    </form>
                </div>
                <div class="size-210 bor10 flex-w flex-col-m p-lr-93 p-tb-30 p-lr-15-lg w-full-md">
                    <div class="flex-w w-full p-b-42">
                        <span class="fs-18 cl5 txt-center size-211">
                            <span class="lnr lnr-map-marker"></span>
                        </span>
                        <div class="size-212 p-t-2">
                            <span class="mtext-110 cl2">
                                Address
                            </span>
                            <p class="stext-115 cl6 size-213 p-t-18">
                            </p>
                        </div>
                    </div>
                    <div class="flex-w w-full p-b-42">
                        <span class="fs-18 cl5 txt-center size-211">
                            <span class="lnr lnr-phone-handset"></span>
                        </span>
                        <div class="size-212 p-t-2">
                            <span class="mtext-110 cl2">
                                Lets Talk
                            </span>
                            <p class="stext-115 cl1 size-213 p-t-18">
                            </p>
                        </div>
                    </div>
                    <div class="flex-w w-full">
                        <span class="fs-18 cl5 txt-center size-211">
                            <span class="lnr lnr-envelope"></span>
                        </span>
                        <div class="size-212 p-t-2">
                            <span class="mtext-110 cl2">
                                Mail Us
                            </span>
                            <p class="stext-115 cl1 size-213 p-t-18">
                                flugapplication@gmail.com
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
}

WebFlug/Views/EmailSetup/SendEmail.cshtml
@model WebFlug.Models.Email
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<title>Flug/Feedback</title>

<!-- Title page -->
<section class="bg-img1 txt-center p-lr-15 p-tb-92" style="background-image: url('/Content/images/aboutus.jpg');">
    <h2 class="ltext-105 cl0 txt-center">
        FeedBack
    </h2>
</section>

<!-- Content page -->
<section class="bg0 p-t-104 p-b-116">
    <div style="margin-left:500px">
        <div class="flex-w flex-tr">
            <div class="size-210 bor10 p-lr-70 p-t-55 p-b-70 p-lr-15-lg w-full-md">
                @using (Html.BeginForm("SendEmail", "EmailSetup", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <h4 class="mtext-105 cl2 txt-center p-b-30">
                        Let Us Know Your Feedback!
                    </h4>

                    <div class="bor8 m-b-30">
                        @Html.TextAreaFor(model => model.Body, new { @class = "stext-111 cl2 plh3 size-120 p-lr-28 p-tb-25", placeholder = "Happy To Hear Your Feedback" })
                    </div>

                    <button class="flex-c-m stext-101 cl0 size-121 bg3 bor1 hov-btn3 p-lr-15 trans-04 pointer">
                        Submit
                    </button>
                }
            </div>

        </div>
    </div>
</section>